<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<OutputPath>$(SolutionDir)x64\$(Configuration)\</OutputPath>
	<LangVersion>latestMajor</LangVersion>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\..\VulkanEngineCore\VulkanEngineCoreCS\VulkanEngineCoreCS.csproj" />
     <ProjectReference Include="..\..\VulkanEngineCore\VulkanEngineCore\VulkanEngineCore.vcxproj" />
     <ProjectReference Include="..\GameScriptLibraryDLL\GameScriptLibraryDLL.csproj" />
     <ProjectReference Include="..\VulkanEngineDLL\VulkanEngineDLL.vcxproj" />
   </ItemGroup>

</Project>
