C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4  FrameBufferShader.vert -o FrameBufferShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.frag -o FrameBufferShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.vert -o Shader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.frag -o Shader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.vert -o LevelShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.frag -o LevelShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceShader.vert -o  SpriteInstanceShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceShader.frag -o  SpriteInstanceShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.vert -o  SpriteInstanceWireFrameShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.frag -o  SpriteInstanceWireFrameShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.vert -o LevelObjectPickerShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.frag -o LevelObjectPickerShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.vert -o LevelObjectWireFrameShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.frag -o LevelObjectWireFrameShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.vert -o  SpriteObjectPickerShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.frag -o  SpriteObjectPickerShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 vertshader.vert -o vertshader.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 fragshader.frag -o fragshader.spv

C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.vert -o ../x64/Debug/FrameBufferShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.frag -o ../x64/Debug/FrameBufferShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.vert -o ../x64/Debug/Shader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.frag -o ../x64/Debug/Shader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.vert -o ../x64/Debug/LevelShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.frag -o ../x64/Debug/LevelShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.vert -o ../x64/Debug/LevelObjectWireFrameShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.frag -o ../x64/Debug/LevelObjectWireFrameShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceShader.vert -o  ../x64/Debug/SpriteInstanceShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceShader.frag -o  ../x64/Debug/SpriteInstanceShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.vert -o  SpriteInstanceWireFrameShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.frag -o  SpriteInstanceWireFrameShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.vert -o ../x64/Debug/LevelObjectPickerShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.frag -o ../x64/Debug/LevelObjectPickerShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.vert -o  ../x64/Debug/SpriteObjectPickerShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.frag -o  ../x64/Debug/SpriteObjectPickerShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.vert -o  ../x64/Debug/SpriteInstanceWireFrameShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteInstanceWireFrameShader.frag -o  ../x64/Debug/SpriteInstanceWireFrameShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 vertshader.vert -o ../x64/Debug/vertshader.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 fragshader.frag -o ../x64/Debug/fragshader.spv

C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.vert -o ../x64/Release/FrameBufferShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.frag -o ../x64/Release/FrameBufferShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.vert -o  ../x64/Release/Shader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.frag -o ../x64/Release/Shader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.vert -o  ../x64/Release/LevelShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.frag -o  ../x64/Release/LevelShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.vert -o ../x64/Release/LevelObjectWireFrameShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.frag -o ../x64/Release/LevelObjectWireFrameShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.vert -o ../x64/Release/LevelObjectPickerShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.frag -o ../x64/Release/LevelObjectPickerShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.vert -o  ../x64/Release/SpriteObjectPickerShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.frag -o  ../x64/Release/SpriteObjectPickerShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 vertshader.vert -o ../x64/Release/vertshader.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 fragshader.frag -o ../x64/Release/fragshader.spv

C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/FrameBufferShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/FrameBufferShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/Shader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/Shader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelObjectWireFrameShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelObjectWireFrameShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelObjectPickerShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/LevelObjectPickerShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.vert -o  ../VulkanGameEngineLevelEditor/bin/Debug/SpriteObjectPickerShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.frag -o  ../VulkanGameEngineLevelEditor/bin/Debug/SpriteObjectPickerShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 vertshader.vert -o ../VulkanGameEngineLevelEditor/bin/Debug/vertshader.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 fragshader.frag -o ../VulkanGameEngineLevelEditor/bin/Debug/fragshader.spv

C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.vert -o ../VulkanGameEngineLevelEditor/bin/Release/FrameBufferShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 FrameBufferShader.frag -o ../VulkanGameEngineLevelEditor/bin/Release/FrameBufferShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Release/Shader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 Shader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Release/Shader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Release/LevelShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Release/LevelShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Release/LevelObjectWireFrameShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectWireFrameShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Release/LevelObjectWireFrameShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.vert -o ../VulkanGameEngineLevelEditor/bin/Release/LevelObjectPickerShader2DVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 LevelObjectPickerShader2D.frag -o ../VulkanGameEngineLevelEditor/bin/Release/LevelObjectPickerShader2DFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.vert -o  ../VulkanGameEngineLevelEditor/bin/Release/SpriteObjectPickerShaderVert.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 SpriteObjectPickerShader.frag -o  ../VulkanGameEngineLevelEditor/bin/Release/SpriteObjectPickerShaderFrag.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 vertshader.vert -o ../VulkanGameEngineLevelEditor/bin/Release/vertshader.spv
C:/VulkanSDK/1.4.313.0/Bin/glslangValidator.exe -V --target-env vulkan1.4 fragshader.frag -o ../VulkanGameEngineLevelEditor/bin/Release/fragshader.spv
pause