<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<OutputPath>$(SolutionDir)x64\$(Configuration)\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>  
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GlmSharp" Version="0.9.8" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VulkanEngineCore\VulkanEngineCoreCS\VulkanEngineCoreCS.csproj" />
    <ProjectReference Include="..\..\VulkanEngineCore\VulkanEngineCore\VulkanEngineCore.vcxproj" />
    <ProjectReference Include="..\VulkanEngineDLL\VulkanEngineDLL.vcxproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="VulkanEngineCoreCS">
      <HintPath>..\..\VulkanEngineCore\VulkanEngineCoreCS\bin\Debug\net8.0\VulkanEngineCoreCS.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>